import './styles/globals.css'
import 'antd/dist/reset.css'

import { Providers } from './providers'
import Header from './components/header/header'
import Footer from './components/footer/footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1 ,maximum-scale=1',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  )
}
